data:
  azurestorageaccountname: XXX
  azurestorageaccountkey: XXX==
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
  namespace: default
---
data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsStorage: XXX==
  BlobStorage: XXX==
apiVersion: v1
kind: Secret
metadata:
  name: img-color
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-color
  namespace: default
  labels:
    app: img-color
spec:
  selector:
    matchLabels:
      app: img-color
  template:
    metadata:
      labels:
        app: img-color
    spec:
      containers:
        - name: img-color
          image: mscommunity20.azurecr.io/img-color
          env:
            - name: AzureFunctionsJobHost__functions__0
              value: ImgProcess
          envFrom:
            - secretRef:
                name: img-color
          resources:
            requests:
              cpu: "1"
              memory: "2G"
          volumeMounts:
            - name: azurefileshare
              mountPath: /mnt/data
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
      imagePullSecrets:
        - name: acr-secret
      volumes:
      - name: azurefileshare
        azureFile:
          secretName: storage-secret
          shareName: model
          readOnly: false
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: img-color
  namespace: default
  labels:
    deploymentName: img-color
spec:
  scaleTargetRef:
    name: img-color
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1 # Optional, Default 0
  maxReplicaCount: 30 # Optional. Default: 100
  triggers:
    - type: azure-blob
      metadata:
        blobContainerName: no-color-image # Required: Name of Azure Blob Storage container
        blobCount: "5" # Optional. Amount of blobs to scale out on. Default: 5 blobs
        connectionFromEnv: BlobStorage # Optional if TriggerAuthentication defined with pod identity or connection string authentication.
        blobPrefix: no-color-image # Optional. Prefix for the Blob. Use this to specifiy sub path for the blobs if required. Default : ""
        blobDelimiter: "/" # Optional. Delimiter for identifying the blob Prefix. Default: "/"
---